import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "./globals.css"
import Providers from "@/components/providers"

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"], // bebas pilih
})

export const metadata: Metadata = {
  title: "Joovlink",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
